[package]
name = "help_sample_mock_package"
version = "0.1.0"
authors = ["Thiago Veronezi <thiago@veronezi.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.3"
